[package]
name = "gba-emulator"
version = "0.1.0"
authors = ["r1cebank <siyuangao@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
strum = "0.19"
strum_macros = "0.19"
simplelog = "^0.7.6"
clap = "2.33.3"
imgui = "0.5.0"
clipboard = "0.5"
glium = { version = "0.27", default-features = true }
imgui-glium-renderer = "0.5.0"
imgui-winit-support = "0.5.0"

[dev-dependencies]
serde = { version = "1.0.117", features = ["derive"] }
serde_json = "1.0.59"