[package]
name = "gba-emulator"
version = "0.1.0"
authors = ["r1cebank <siyuangao@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
opengl = ["imgui-gfx-renderer/opengl"]
directx = ["imgui-gfx-renderer/directx"]
default = ["opengl"]

[dependencies]
log = "0.4"
strum = "0.19"
strum_macros = "0.19"
simplelog = "^0.7.6"
clap = "2.33.3"
imgui = "0.5.0"
clipboard = "0.5"
gfx = "0.18"
glutin = "0.21"
gfx_device_gl = "0.16.2"
gfx_window_glutin = "0.31.0"
imgui-winit-support = { version = "0.5.0", default-features = false, features = ["winit-19"]}
imgui-gfx-renderer = "0.5.0"

[dev-dependencies]
serde = { version = "1.0.117", features = ["derive"] }
serde_json = "1.0.59"