use crate::cpu::instruction::{
    Address, AddressLocation, BitArthOperationType, BitOperationTarget, BitTestLocation,
    BitTestSource, BitTestType, Condition, Instruction, OperationType, Register, TargetType, Value,
};

/// SM83 non prefixed instruction map
///
pub static INSTRUCTION_MAP: [[Instruction; 0x10]; 0x10] = [
    // 0
    [
        Instruction::NOP,
        Instruction::LD(OperationType::ValueToRegister(Register::BC, Value::D16)),
        Instruction::LD(OperationType::RegisterToAddress(Address::BC, Register::A)),
        Instruction::INC(TargetType::Register(Register::BC)),
        Instruction::INC(TargetType::Register(Register::B)),
        Instruction::DEC(TargetType::Register(Register::B)),
        Instruction::LD(OperationType::ValueToRegister(Register::B, Value::D8)),
        Instruction::RLCA,
        Instruction::LD(OperationType::RegisterToAddress(Address::A16, Register::SP)),
        Instruction::ADD(OperationType::RegisterToRegister(
            Register::HL,
            Register::BC,
        )),
        Instruction::LD(OperationType::AddressToRegister(Register::A, Address::BC)),
        Instruction::DEC(TargetType::Register(Register::BC)),
        Instruction::INC(TargetType::Register(Register::C)),
        Instruction::DEC(TargetType::Register(Register::C)),
        Instruction::LD(OperationType::ValueToRegister(Register::C, Value::D8)),
        Instruction::RRCA,
    ],
    // 1
    [
        Instruction::STOP,
        Instruction::LD(OperationType::ValueToRegister(Register::DE, Value::D16)),
        Instruction::LD(OperationType::RegisterToAddress(Address::DE, Register::A)),
        Instruction::INC(TargetType::Register(Register::DE)),
        Instruction::INC(TargetType::Register(Register::D)),
        Instruction::DEC(TargetType::Register(Register::D)),
        Instruction::LD(OperationType::ValueToRegister(Register::D, Value::D8)),
        Instruction::RLA,
        Instruction::JR(Condition::Always, Address::R8),
        Instruction::ADD(OperationType::RegisterToRegister(
            Register::HL,
            Register::DE,
        )),
        Instruction::LD(OperationType::AddressToRegister(Register::A, Address::DE)),
        Instruction::DEC(TargetType::Register(Register::DE)),
        Instruction::INC(TargetType::Register(Register::E)),
        Instruction::DEC(TargetType::Register(Register::E)),
        Instruction::LD(OperationType::ValueToRegister(Register::E, Value::D8)),
        Instruction::RRA,
    ],
    // 2
    [
        Instruction::JR(Condition::NotZero, Address::R8),
        Instruction::LD(OperationType::ValueToRegister(Register::HL, Value::D16)),
        Instruction::LD(OperationType::RegisterToAddress(Address::HLP, Register::A)),
        Instruction::INC(TargetType::Register(Register::HL)),
        Instruction::INC(TargetType::Register(Register::H)),
        Instruction::DEC(TargetType::Register(Register::H)),
        Instruction::LD(OperationType::ValueToRegister(Register::H, Value::D8)),
        Instruction::DAA,
        Instruction::JR(Condition::Zero, Address::R8),
        Instruction::ADD(OperationType::RegisterToRegister(
            Register::HL,
            Register::HL,
        )),
        Instruction::LD(OperationType::AddressToRegister(Register::A, Address::HLP)),
        Instruction::DEC(TargetType::Register(Register::HL)),
        Instruction::INC(TargetType::Register(Register::L)),
        Instruction::DEC(TargetType::Register(Register::L)),
        Instruction::LD(OperationType::ValueToRegister(Register::L, Value::D8)),
        Instruction::CPL,
    ],
    // 3
    [
        Instruction::JR(Condition::NotCarry, Address::R8),
        Instruction::LD(OperationType::ValueToRegister(Register::SP, Value::D16)),
        Instruction::LD(OperationType::RegisterToAddress(Address::HLM, Register::A)),
        Instruction::INC(TargetType::Register(Register::SP)),
        Instruction::INC(TargetType::Address(Address::HL)),
        Instruction::DEC(TargetType::Address(Address::HL)),
        Instruction::LD(OperationType::ValueToAddress(Address::HL, Value::D8)),
        Instruction::SCF,
        Instruction::JR(Condition::Carry, Address::R8),
        Instruction::ADD(OperationType::RegisterToRegister(
            Register::HL,
            Register::SP,
        )),
        Instruction::LD(OperationType::AddressToRegister(Register::A, Address::HLM)),
        Instruction::DEC(TargetType::Register(Register::SP)),
        Instruction::INC(TargetType::Register(Register::A)),
        Instruction::DEC(TargetType::Register(Register::A)),
        Instruction::LD(OperationType::ValueToRegister(Register::A, Value::D8)),
        Instruction::CCF,
    ],
    // 4
    [
        Instruction::LD(OperationType::RegisterToRegister(Register::B, Register::B)),
        Instruction::LD(OperationType::RegisterToRegister(Register::B, Register::C)),
        Instruction::LD(OperationType::RegisterToRegister(Register::B, Register::D)),
        Instruction::LD(OperationType::RegisterToRegister(Register::B, Register::E)),
        Instruction::LD(OperationType::RegisterToRegister(Register::B, Register::H)),
        Instruction::LD(OperationType::RegisterToRegister(Register::B, Register::L)),
        Instruction::LD(OperationType::AddressToRegister(Register::B, Address::HL)),
        Instruction::LD(OperationType::RegisterToRegister(Register::B, Register::A)),
        Instruction::LD(OperationType::RegisterToRegister(Register::C, Register::B)),
        Instruction::LD(OperationType::RegisterToRegister(Register::C, Register::C)),
        Instruction::LD(OperationType::RegisterToRegister(Register::C, Register::D)),
        Instruction::LD(OperationType::RegisterToRegister(Register::C, Register::E)),
        Instruction::LD(OperationType::RegisterToRegister(Register::C, Register::H)),
        Instruction::LD(OperationType::RegisterToRegister(Register::C, Register::L)),
        Instruction::LD(OperationType::AddressToRegister(Register::C, Address::HL)),
        Instruction::LD(OperationType::RegisterToRegister(Register::C, Register::A)),
    ],
    // 5
    [
        Instruction::LD(OperationType::RegisterToRegister(Register::D, Register::B)),
        Instruction::LD(OperationType::RegisterToRegister(Register::D, Register::C)),
        Instruction::LD(OperationType::RegisterToRegister(Register::D, Register::D)),
        Instruction::LD(OperationType::RegisterToRegister(Register::D, Register::E)),
        Instruction::LD(OperationType::RegisterToRegister(Register::D, Register::H)),
        Instruction::LD(OperationType::RegisterToRegister(Register::D, Register::L)),
        Instruction::LD(OperationType::AddressToRegister(Register::D, Address::HL)),
        Instruction::LD(OperationType::RegisterToRegister(Register::D, Register::A)),
        Instruction::LD(OperationType::RegisterToRegister(Register::E, Register::B)),
        Instruction::LD(OperationType::RegisterToRegister(Register::E, Register::C)),
        Instruction::LD(OperationType::RegisterToRegister(Register::E, Register::D)),
        Instruction::LD(OperationType::RegisterToRegister(Register::E, Register::E)),
        Instruction::LD(OperationType::RegisterToRegister(Register::E, Register::H)),
        Instruction::LD(OperationType::RegisterToRegister(Register::E, Register::L)),
        Instruction::LD(OperationType::AddressToRegister(Register::E, Address::HL)),
        Instruction::LD(OperationType::RegisterToRegister(Register::E, Register::A)),
    ],
    // 6
    [
        Instruction::LD(OperationType::RegisterToRegister(Register::H, Register::B)),
        Instruction::LD(OperationType::RegisterToRegister(Register::H, Register::C)),
        Instruction::LD(OperationType::RegisterToRegister(Register::H, Register::D)),
        Instruction::LD(OperationType::RegisterToRegister(Register::H, Register::E)),
        Instruction::LD(OperationType::RegisterToRegister(Register::H, Register::H)),
        Instruction::LD(OperationType::RegisterToRegister(Register::H, Register::L)),
        Instruction::LD(OperationType::AddressToRegister(Register::H, Address::HL)),
        Instruction::LD(OperationType::RegisterToRegister(Register::H, Register::A)),
        Instruction::LD(OperationType::RegisterToRegister(Register::L, Register::B)),
        Instruction::LD(OperationType::RegisterToRegister(Register::L, Register::C)),
        Instruction::LD(OperationType::RegisterToRegister(Register::L, Register::D)),
        Instruction::LD(OperationType::RegisterToRegister(Register::L, Register::E)),
        Instruction::LD(OperationType::RegisterToRegister(Register::L, Register::H)),
        Instruction::LD(OperationType::RegisterToRegister(Register::L, Register::L)),
        Instruction::LD(OperationType::AddressToRegister(Register::L, Address::HL)),
        Instruction::LD(OperationType::RegisterToRegister(Register::L, Register::A)),
    ],
    // 7
    [
        Instruction::LD(OperationType::RegisterToAddress(Address::HL, Register::B)),
        Instruction::LD(OperationType::RegisterToAddress(Address::HL, Register::C)),
        Instruction::LD(OperationType::RegisterToAddress(Address::HL, Register::D)),
        Instruction::LD(OperationType::RegisterToAddress(Address::HL, Register::E)),
        Instruction::LD(OperationType::RegisterToAddress(Address::HL, Register::H)),
        Instruction::LD(OperationType::RegisterToAddress(Address::HL, Register::L)),
        Instruction::HALT,
        Instruction::LD(OperationType::RegisterToAddress(Address::HL, Register::A)),
        Instruction::LD(OperationType::RegisterToRegister(Register::A, Register::B)),
        Instruction::LD(OperationType::RegisterToRegister(Register::A, Register::C)),
        Instruction::LD(OperationType::RegisterToRegister(Register::A, Register::D)),
        Instruction::LD(OperationType::RegisterToRegister(Register::A, Register::E)),
        Instruction::LD(OperationType::RegisterToRegister(Register::A, Register::H)),
        Instruction::LD(OperationType::RegisterToRegister(Register::A, Register::L)),
        Instruction::LD(OperationType::AddressToRegister(Register::A, Address::HL)),
        Instruction::LD(OperationType::RegisterToRegister(Register::A, Register::A)),
    ],
    // 8
    [
        Instruction::ADD(OperationType::RegisterToRegister(Register::A, Register::B)),
        Instruction::ADD(OperationType::RegisterToRegister(Register::A, Register::C)),
        Instruction::ADD(OperationType::RegisterToRegister(Register::A, Register::D)),
        Instruction::ADD(OperationType::RegisterToRegister(Register::A, Register::E)),
        Instruction::ADD(OperationType::RegisterToRegister(Register::A, Register::H)),
        Instruction::ADD(OperationType::RegisterToRegister(Register::A, Register::L)),
        Instruction::ADD(OperationType::AddressToRegister(Register::A, Address::HL)),
        Instruction::ADD(OperationType::RegisterToRegister(Register::A, Register::A)),
        Instruction::ADC(OperationType::RegisterToRegister(Register::A, Register::B)),
        Instruction::ADC(OperationType::RegisterToRegister(Register::A, Register::C)),
        Instruction::ADC(OperationType::RegisterToRegister(Register::A, Register::D)),
        Instruction::ADC(OperationType::RegisterToRegister(Register::A, Register::E)),
        Instruction::ADC(OperationType::RegisterToRegister(Register::A, Register::H)),
        Instruction::ADC(OperationType::RegisterToRegister(Register::A, Register::L)),
        Instruction::ADC(OperationType::AddressToRegister(Register::A, Address::HL)),
        Instruction::ADC(OperationType::RegisterToRegister(Register::A, Register::A)),
    ],
    // 9
    [
        Instruction::SUB(OperationType::RegisterToRegister(Register::A, Register::B)),
        Instruction::SUB(OperationType::RegisterToRegister(Register::A, Register::C)),
        Instruction::SUB(OperationType::RegisterToRegister(Register::A, Register::D)),
        Instruction::SUB(OperationType::RegisterToRegister(Register::A, Register::E)),
        Instruction::SUB(OperationType::RegisterToRegister(Register::A, Register::H)),
        Instruction::SUB(OperationType::RegisterToRegister(Register::A, Register::L)),
        Instruction::SUB(OperationType::AddressToRegister(Register::A, Address::HL)),
        Instruction::SUB(OperationType::RegisterToRegister(Register::A, Register::A)),
        Instruction::SBC(OperationType::RegisterToRegister(Register::A, Register::B)),
        Instruction::SBC(OperationType::RegisterToRegister(Register::A, Register::C)),
        Instruction::SBC(OperationType::RegisterToRegister(Register::A, Register::D)),
        Instruction::SBC(OperationType::RegisterToRegister(Register::A, Register::E)),
        Instruction::SBC(OperationType::RegisterToRegister(Register::A, Register::H)),
        Instruction::SBC(OperationType::RegisterToRegister(Register::A, Register::L)),
        Instruction::SBC(OperationType::AddressToRegister(Register::A, Address::HL)),
        Instruction::SBC(OperationType::RegisterToRegister(Register::A, Register::A)),
    ],
    // a
    [
        Instruction::AND(OperationType::RegisterToRegister(Register::A, Register::B)),
        Instruction::AND(OperationType::RegisterToRegister(Register::A, Register::C)),
        Instruction::AND(OperationType::RegisterToRegister(Register::A, Register::D)),
        Instruction::AND(OperationType::RegisterToRegister(Register::A, Register::E)),
        Instruction::AND(OperationType::RegisterToRegister(Register::A, Register::H)),
        Instruction::AND(OperationType::RegisterToRegister(Register::A, Register::L)),
        Instruction::AND(OperationType::AddressToRegister(Register::A, Address::HL)),
        Instruction::AND(OperationType::RegisterToRegister(Register::A, Register::A)),
        Instruction::XOR(OperationType::RegisterToRegister(Register::A, Register::B)),
        Instruction::XOR(OperationType::RegisterToRegister(Register::A, Register::C)),
        Instruction::XOR(OperationType::RegisterToRegister(Register::A, Register::D)),
        Instruction::XOR(OperationType::RegisterToRegister(Register::A, Register::E)),
        Instruction::XOR(OperationType::RegisterToRegister(Register::A, Register::H)),
        Instruction::XOR(OperationType::RegisterToRegister(Register::A, Register::L)),
        Instruction::XOR(OperationType::AddressToRegister(Register::A, Address::HL)),
        Instruction::XOR(OperationType::RegisterToRegister(Register::A, Register::A)),
    ],
    // b
    [
        Instruction::OR(OperationType::RegisterToRegister(Register::A, Register::B)),
        Instruction::OR(OperationType::RegisterToRegister(Register::A, Register::C)),
        Instruction::OR(OperationType::RegisterToRegister(Register::A, Register::D)),
        Instruction::OR(OperationType::RegisterToRegister(Register::A, Register::E)),
        Instruction::OR(OperationType::RegisterToRegister(Register::A, Register::H)),
        Instruction::OR(OperationType::RegisterToRegister(Register::A, Register::L)),
        Instruction::OR(OperationType::AddressToRegister(Register::A, Address::HL)),
        Instruction::OR(OperationType::RegisterToRegister(Register::A, Register::A)),
        Instruction::CP(OperationType::RegisterToRegister(Register::A, Register::B)),
        Instruction::CP(OperationType::RegisterToRegister(Register::A, Register::C)),
        Instruction::CP(OperationType::RegisterToRegister(Register::A, Register::D)),
        Instruction::CP(OperationType::RegisterToRegister(Register::A, Register::E)),
        Instruction::CP(OperationType::RegisterToRegister(Register::A, Register::H)),
        Instruction::CP(OperationType::RegisterToRegister(Register::A, Register::L)),
        Instruction::CP(OperationType::AddressToRegister(Register::A, Address::HL)),
        Instruction::CP(OperationType::RegisterToRegister(Register::A, Register::A)),
    ],
    // c
    [
        Instruction::RET(Condition::NotZero),
        Instruction::POP(Register::BC),
        Instruction::JP(Condition::NotZero, Address::A16),
        Instruction::JP(Condition::Always, Address::A16),
        Instruction::CALL(Condition::NotZero, Address::A16),
        Instruction::PUSH(Register::BC),
        Instruction::ADD(OperationType::ValueToRegister(Register::A, Value::D8)),
        Instruction::RST(AddressLocation::X00H),
        Instruction::RET(Condition::Zero),
        Instruction::RET(Condition::Always),
        Instruction::JP(Condition::Zero, Address::A16),
        Instruction::PREFIX,
        Instruction::CALL(Condition::Zero, Address::A16),
        Instruction::CALL(Condition::Always, Address::A16),
        Instruction::ADC(OperationType::ValueToRegister(Register::A, Value::D8)),
        Instruction::RST(AddressLocation::X08H),
    ],
    // d
    [
        Instruction::RET(Condition::NotCarry),
        Instruction::POP(Register::DE),
        Instruction::JP(Condition::NotCarry, Address::A16),
        Instruction::NAI,
        Instruction::CALL(Condition::NotCarry, Address::A16),
        Instruction::PUSH(Register::DE),
        Instruction::SUB(OperationType::ValueToRegister(Register::A, Value::D8)),
        Instruction::RST(AddressLocation::X10H),
        Instruction::RET(Condition::Carry),
        Instruction::RETI,
        Instruction::JP(Condition::Carry, Address::A16),
        Instruction::NAI,
        Instruction::CALL(Condition::Carry, Address::A16),
        Instruction::NAI,
        Instruction::SBC(OperationType::ValueToRegister(Register::A, Value::D8)),
        Instruction::RST(AddressLocation::X18H),
    ],
    // e
    [
        Instruction::LDH(OperationType::RegisterToAddress(Address::A8, Register::A)),
        Instruction::POP(Register::HL),
        Instruction::LD(OperationType::RegisterToAddress(Address::C, Register::A)),
        Instruction::NAI,
        Instruction::NAI,
        Instruction::PUSH(Register::HL),
        Instruction::AND(OperationType::ValueToRegister(Register::A, Value::D8)),
        Instruction::RST(AddressLocation::X20H),
        Instruction::ADD(OperationType::ValueToRegister(Register::SP, Value::R8)),
        Instruction::JP(Condition::Always, Address::HL),
        Instruction::LD(OperationType::RegisterToAddress(Address::A16, Register::A)),
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::XOR(OperationType::ValueToRegister(Register::A, Value::D8)),
        Instruction::RST(AddressLocation::X28H),
    ],
    // f
    [
        Instruction::LDH(OperationType::AddressToRegister(Register::A, Address::A8)),
        Instruction::POP(Register::AF),
        Instruction::LD(OperationType::AddressToRegister(Register::A, Address::C)),
        Instruction::DI,
        Instruction::NAI,
        Instruction::PUSH(Register::AF),
        Instruction::OR(OperationType::ValueToRegister(Register::A, Value::D8)),
        Instruction::RST(AddressLocation::X30H),
        Instruction::LD(OperationType::RegisterToRegister(
            Register::HL,
            Register::SPP,
        )),
        Instruction::LD(OperationType::RegisterToRegister(
            Register::SP,
            Register::HL,
        )),
        Instruction::LD(OperationType::AddressToRegister(Register::A, Address::A16)),
        Instruction::EI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::CP(OperationType::ValueToRegister(Register::A, Value::D8)),
        Instruction::RST(AddressLocation::X38H),
    ],
];

/// SM83 prefixed instruction map
///
pub static PREFIX_INSTRUCTION_MAP: [[Instruction; 0x10]; 0x10] = [
    // 0
    [
        Instruction::RLC(BitArthOperationType::ToRegister(BitOperationTarget::B)),
        Instruction::RLC(BitArthOperationType::ToRegister(BitOperationTarget::C)),
        Instruction::RLC(BitArthOperationType::ToRegister(BitOperationTarget::D)),
        Instruction::RLC(BitArthOperationType::ToRegister(BitOperationTarget::E)),
        Instruction::RLC(BitArthOperationType::ToRegister(BitOperationTarget::H)),
        Instruction::RLC(BitArthOperationType::ToRegister(BitOperationTarget::L)),
        Instruction::RLC(BitArthOperationType::ToAddress(BitOperationTarget::HL)),
        Instruction::RLC(BitArthOperationType::ToRegister(BitOperationTarget::A)),
        Instruction::RRC(BitArthOperationType::ToRegister(BitOperationTarget::B)),
        Instruction::RRC(BitArthOperationType::ToRegister(BitOperationTarget::C)),
        Instruction::RRC(BitArthOperationType::ToRegister(BitOperationTarget::D)),
        Instruction::RRC(BitArthOperationType::ToRegister(BitOperationTarget::E)),
        Instruction::RRC(BitArthOperationType::ToRegister(BitOperationTarget::H)),
        Instruction::RRC(BitArthOperationType::ToRegister(BitOperationTarget::L)),
        Instruction::RRC(BitArthOperationType::ToAddress(BitOperationTarget::HL)),
        Instruction::RRC(BitArthOperationType::ToRegister(BitOperationTarget::A)),
    ],
    // 1
    [
        Instruction::RL(BitArthOperationType::ToRegister(BitOperationTarget::B)),
        Instruction::RL(BitArthOperationType::ToRegister(BitOperationTarget::C)),
        Instruction::RL(BitArthOperationType::ToRegister(BitOperationTarget::D)),
        Instruction::RL(BitArthOperationType::ToRegister(BitOperationTarget::E)),
        Instruction::RL(BitArthOperationType::ToRegister(BitOperationTarget::H)),
        Instruction::RL(BitArthOperationType::ToRegister(BitOperationTarget::L)),
        Instruction::RL(BitArthOperationType::ToAddress(BitOperationTarget::HL)),
        Instruction::RL(BitArthOperationType::ToRegister(BitOperationTarget::A)),
        Instruction::RR(BitArthOperationType::ToRegister(BitOperationTarget::B)),
        Instruction::RR(BitArthOperationType::ToRegister(BitOperationTarget::C)),
        Instruction::RR(BitArthOperationType::ToRegister(BitOperationTarget::D)),
        Instruction::RR(BitArthOperationType::ToRegister(BitOperationTarget::E)),
        Instruction::RR(BitArthOperationType::ToRegister(BitOperationTarget::H)),
        Instruction::RR(BitArthOperationType::ToRegister(BitOperationTarget::L)),
        Instruction::RR(BitArthOperationType::ToAddress(BitOperationTarget::HL)),
        Instruction::RR(BitArthOperationType::ToRegister(BitOperationTarget::A)),
    ],
    // 2
    [
        Instruction::SLA(BitArthOperationType::ToRegister(BitOperationTarget::B)),
        Instruction::SLA(BitArthOperationType::ToRegister(BitOperationTarget::C)),
        Instruction::SLA(BitArthOperationType::ToRegister(BitOperationTarget::D)),
        Instruction::SLA(BitArthOperationType::ToRegister(BitOperationTarget::E)),
        Instruction::SLA(BitArthOperationType::ToRegister(BitOperationTarget::H)),
        Instruction::SLA(BitArthOperationType::ToRegister(BitOperationTarget::L)),
        Instruction::SLA(BitArthOperationType::ToAddress(BitOperationTarget::HL)),
        Instruction::SLA(BitArthOperationType::ToRegister(BitOperationTarget::A)),
        Instruction::SRA(BitArthOperationType::ToRegister(BitOperationTarget::B)),
        Instruction::SRA(BitArthOperationType::ToRegister(BitOperationTarget::C)),
        Instruction::SRA(BitArthOperationType::ToRegister(BitOperationTarget::D)),
        Instruction::SRA(BitArthOperationType::ToRegister(BitOperationTarget::E)),
        Instruction::SRA(BitArthOperationType::ToRegister(BitOperationTarget::H)),
        Instruction::SRA(BitArthOperationType::ToRegister(BitOperationTarget::L)),
        Instruction::SRA(BitArthOperationType::ToAddress(BitOperationTarget::HL)),
        Instruction::SRA(BitArthOperationType::ToRegister(BitOperationTarget::A)),
    ],
    // 3
    [
        Instruction::SWAP(BitArthOperationType::ToRegister(BitOperationTarget::B)),
        Instruction::SWAP(BitArthOperationType::ToRegister(BitOperationTarget::C)),
        Instruction::SWAP(BitArthOperationType::ToRegister(BitOperationTarget::D)),
        Instruction::SWAP(BitArthOperationType::ToRegister(BitOperationTarget::E)),
        Instruction::SWAP(BitArthOperationType::ToRegister(BitOperationTarget::H)),
        Instruction::SWAP(BitArthOperationType::ToRegister(BitOperationTarget::L)),
        Instruction::SWAP(BitArthOperationType::ToAddress(BitOperationTarget::HL)),
        Instruction::SWAP(BitArthOperationType::ToRegister(BitOperationTarget::A)),
        Instruction::SRL(BitArthOperationType::ToRegister(BitOperationTarget::B)),
        Instruction::SRL(BitArthOperationType::ToRegister(BitOperationTarget::C)),
        Instruction::SRL(BitArthOperationType::ToRegister(BitOperationTarget::D)),
        Instruction::SRL(BitArthOperationType::ToRegister(BitOperationTarget::E)),
        Instruction::SRL(BitArthOperationType::ToRegister(BitOperationTarget::H)),
        Instruction::SRL(BitArthOperationType::ToRegister(BitOperationTarget::L)),
        Instruction::SRL(BitArthOperationType::ToAddress(BitOperationTarget::HL)),
        Instruction::SRL(BitArthOperationType::ToRegister(BitOperationTarget::A)),
    ],
    // 4
    [
        Instruction::BIT(BitTestType::FromRegister(
            BitTestLocation::B0,
            BitTestSource::B,
        )),
        Instruction::BIT(BitTestType::FromRegister(
            BitTestLocation::B0,
            BitTestSource::C,
        )),
        Instruction::BIT(BitTestType::FromRegister(
            BitTestLocation::B0,
            BitTestSource::D,
        )),
        Instruction::BIT(BitTestType::FromRegister(
            BitTestLocation::B0,
            BitTestSource::E,
        )),
        Instruction::BIT(BitTestType::FromRegister(
            BitTestLocation::B0,
            BitTestSource::H,
        )),
        Instruction::BIT(BitTestType::FromRegister(
            BitTestLocation::B0,
            BitTestSource::L,
        )),
        Instruction::BIT(BitTestType::FromAddress(
            BitTestLocation::B0,
            BitTestSource::HL,
        )),
        Instruction::BIT(BitTestType::FromRegister(
            BitTestLocation::B0,
            BitTestSource::A,
        )),
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
    ],
    // 5
    [
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
    ],
    // 6
    [
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
    ],
    // 7
    [
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
    ],
    // 8
    [
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
    ],
    // 9
    [
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
    ],
    // a
    [
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
    ],
    // b
    [
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
    ],
    // c
    [
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
    ],
    // d
    [
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
    ],
    // e
    [
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
    ],
    // f
    [
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
        Instruction::NAI,
    ],
];
